/*
 * This headerfile defines for each interrupt-source whether it should be managed by ATmighty (true) or by the user (false).
 */

#ifndef CONFIG_INTERRUPTCONFIG_H_
#define CONFIG_INTERRUPTCONFIG_H_


//Timer0:
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_TOV0 true
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_OCF0A true
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_OCF0B true

//Timer1:
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_TOV1 true
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_OCF1A true
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_OCF1B true
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_OCF1C true
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_ICF1 true

//Timer2:
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_TOV2 true
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_OCF2A true
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_OCF2B true

//Timer3:
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_TOV3 true
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_OCF3A true
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_OCF3B true
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_OCF3C true
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_ICF3 true

//Timer4:
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_TOV4 true
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_OCF4A true
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_OCF4B true
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_OCF4C true
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_ICF4 true

//Timer5:
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_TOV5 true
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_OCF5A true
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_OCF5B true
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_OCF5C true
#define ATMIGHTY_INTERRUPTCONFIG_MANAGE_ICF5 true

#endif /* CONFIG_INTERRUPTCONFIG_H_ */
